server:
  port: 8080
  tomcat:
    max-threads: 500
    min-spare-threads: 50

spring:
  application:
    name: openai-starter-test
  jackson:
    default-property-inclusion: non_null

openai:
  token:   #对应openai api key
  timeout: 10000